# Generated by Django 6.0.5 on 2026-08-05 02:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pengaduan', '0001_initial'), ('pengaduan', '0002_alter_bidang_id_alter_customuser_id_alter_laporan_id_and_more'), ('pengaduan', '0003_laporan_lampiran'), ('pengaduan', '0004_alter_laporan_created_at'), ('pengaduan', '0005_customuser_foto_profil'), ('pengaduan', '0006_alter_bidang_id_alter_customuser_id_alter_laporan_id'), ('pengaduan', '0007_laporan_prioritas'), ('pengaduan', '0008_customuser_nomor_telepon'), ('pengaduan', '0009_remove_laporan_prioritas_laporan_estimasi_penanganan'), ('pengaduan', '0010_laporan_estimasi_mulai'), ('pengaduan', '0011_customuser_is_teknisi_laporan_teknisi_bertugas'), ('pengaduan', '0012_remove_customuser_is_teknisi_and_more'), ('pengaduan', '0013_customuser_is_teknisi_laporan_teknisi_bertugas'), ('pengaduan', '0014_customuser_is_verified_teknisi_and_more'), ('pengaduan', '0015_laporan_prioritas'), ('pengaduan', '0016_alter_laporan_prioritas'), ('pengaduan', '0017_alter_laporan_prioritas')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Bidang')),
            ],
            options={
                'verbose_name_plural': 'Bidang',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='pengaduan.bidang', verbose_name='Asal Bidang')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Profil')),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('is_teknisi', models.BooleanField(default=False, verbose_name='Status Teknisi')),
                ('is_verified_teknisi', models.BooleanField(default=False, verbose_name='Teknisi Terverifikasi')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Masalah')),
                ('kategori', models.CharField(choices=[('jaringan_terputus', 'Jaringan Terputus / Mati Total'), ('koneksi_lambat', 'Koneksi Lambat / Tidak Stabil'), ('pemasangan_baru', 'Pemasangan Jaringan Baru'), ('kendala_intranet', 'Kendala Akses Intranet / Aplikasi Lokal'), ('kerusakan_fisik', 'Kerusakan Fisik Perangkat Jaringan'), ('relokasi_titik', 'Relokasi Titik Jaringan'), ('permintaan_konfigurasi', 'Permintaan Konfigurasi Jaringan')], max_length=50, verbose_name='Kategori Masalah')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Detail')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='menunggu', max_length=20, verbose_name='Status Laporan')),
                ('solusi', models.TextField(blank=True, null=True, verbose_name='Solusi yang Diberikan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Lapor')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate')),
                ('bidang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_bidang', to='pengaduan.bidang', verbose_name='Bidang Pelapor')),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_saya', to=settings.AUTH_USER_MODEL, verbose_name='Nama Pelapor')),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='lampiran/', verbose_name='Lampiran')),
                ('estimasi_penanganan', models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Penanganan')),
                ('estimasi_mulai', models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Mulai Dikerjakan')),
                ('teknisi_bertugas', models.ForeignKey(blank=True, limit_choices_to={'is_teknisi': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_teknisi', to=settings.AUTH_USER_MODEL, verbose_name='Teknisi Bertugas')),
                ('bukti_penyelesaian', models.ImageField(blank=True, null=True, upload_to='bukti/', verbose_name='Foto Bukti Penyelesaian')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating (1-5)')),
                ('ulasan', models.TextField(blank=True, null=True, verbose_name='Ulasan Pelapor')),
                ('waktu_diambil', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai Dikerjakan')),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('prioritas', models.CharField(choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4')], default='level_1', max_length=20, verbose_name='Prioritas Laporan')),
            ],
            options={
                'verbose_name_plural': 'Laporan',
                'ordering': ['-created_at'],
            },
        ),
    ]
