# Generated by Django 4.2.30 on 2026-05-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(choices=[('jaringan_terputus', 'Jaringan Terputus / Mati Total'), ('koneksi_lambat', 'Koneksi Lambat / Tidak Stabil'), ('pemasangan_baru', 'Pemasangan Jaringan Baru'), ('kendala_intranet', 'Kendala Akses Intranet / Aplikasi Lokal'), ('kerusakan_fisik', 'Kerusakan Fisik Perangkat Jaringan'), ('relokasi_titik', 'Relokasi Titik Jaringan'), ('permintaan_konfigurasi', 'Permintaan Konfigurasi Jaringan')], max_length=50, verbose_name='Kategori Masalah'),
        ),
    ]
