# Generated by Django 4.2.30 on 2026-05-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0002_alter_bidang_id_alter_customuser_id_alter_laporan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='lampiran',
            field=models.FileField(blank=True, null=True, upload_to='lampiran/', verbose_name='Lampiran'),
        ),
    ]
