# Generated by Django 4.2.30 on 2026-05-11 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0003_laporan_lampiran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Lapor'),
        ),
    ]
