# Generated by Django 4.2.30 on 2026-05-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0004_alter_laporan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Profil'),
        ),
    ]
