# Generated by Django 6.0.5 on 2026-05-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0005_customuser_foto_profil'),
    ]

    operations = []
