# Generated by Django 6.0.5 on 2026-05-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0006_alter_bidang_id_alter_customuser_id_alter_laporan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='prioritas',
            field=models.CharField(choices=[('rendah', 'Prioritas Rendah'), ('sedang', 'Prioritas Sedang'), ('tinggi', 'Prioritas Tinggi')], default='sedang', max_length=20, verbose_name='Prioritas'),
        ),
    ]
