# Generated by Django 4.2.30 on 2026-05-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0007_laporan_prioritas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon'),
        ),
    ]
