# Generated by Django 6.0.5 on 2026-05-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0008_customuser_nomor_telepon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='prioritas',
        ),
        migrations.AddField(
            model_name='laporan',
            name='estimasi_penanganan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Penanganan'),
        ),
    ]
