# Generated by Django 6.0.5 on 2026-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0009_remove_laporan_prioritas_laporan_estimasi_penanganan'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='estimasi_mulai',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Mulai Dikerjakan'),
        ),
    ]
