# Generated by Django 6.0.5 on 2026-05-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0011_customuser_is_teknisi_laporan_teknisi_bertugas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_teknisi',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='teknisi_bertugas',
        ),
    ]
