# Generated by Django 6.0.5 on 2026-05-26 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0012_remove_customuser_is_teknisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teknisi',
            field=models.BooleanField(default=False, verbose_name='Status Teknisi'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='teknisi_bertugas',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teknisi': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_teknisi', to=settings.AUTH_USER_MODEL, verbose_name='Teknisi Bertugas'),
        ),
    ]
