# Generated by Django 6.0.5 on 2026-05-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0013_customuser_is_teknisi_laporan_teknisi_bertugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_teknisi',
            field=models.BooleanField(default=False, verbose_name='Teknisi Terverifikasi'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='bukti_penyelesaian',
            field=models.ImageField(blank=True, null=True, upload_to='bukti/', verbose_name='Foto Bukti Penyelesaian'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating (1-5)'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='ulasan',
            field=models.TextField(blank=True, null=True, verbose_name='Ulasan Pelapor'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='waktu_diambil',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai Dikerjakan'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai'),
        ),
    ]
