# Generated by Django 4.2.30 on 2026-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0014_customuser_is_verified_teknisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='prioritas',
            field=models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('mendesak', 'Mendesak')], default='rendah', max_length=20, verbose_name='Prioritas Laporan'),
        ),
    ]
