# Generated by Django 4.2.30 on 2026-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0015_laporan_prioritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='prioritas',
            field=models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('darurat', 'Darurat')], default='rendah', max_length=20, verbose_name='Prioritas Laporan'),
        ),
    ]
