# Generated by Django 4.2.30 on 2026-06-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0016_alter_laporan_prioritas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='prioritas',
            field=models.CharField(choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4')], default='level_1', max_length=20, verbose_name='Prioritas Laporan'),
        ),
    ]
